"use client";
import { useEffect } from "react";
import Navbar from "@/components/general/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import "./css/fonts.css";
import { createContext, useContext, useState } from "react";
import { WebsiteLanguage } from "@/constants/display-language/website-languages";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
type LanguageContextType = {
  language: string;
  setLanguage: (language: string) => void;
};
const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: (language) => undefined,
});
export function useLanguage() {
  return useContext(LanguageContext);
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [language, setLanguage] = useState("en");

  return (
    <html lang={language}>
      <body
        className={`${inter.className} bg-gradient-to-r from-[#1C1503] to-black`}
      >
        <LanguageContext.Provider value={{ language, setLanguage }}>
          <Navbar />
          {children}
        </LanguageContext.Provider>
      </body>
    </html>
  );
}
